# Permalinks
permalink:           pretty

# Setup
title:               Darien Mitchell-Tontar
tagline:             Practicing Blogging Skills with Metis
url:                 http://darienpmt.github.io
paginate:            2
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Darien Mitchell-Tontar
  email:             darienpmt@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/darienpmt

# Gems
gems:
  - not sure what this does
  - nor this

# Page List
pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/index.html'
